controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

steam_authentication_callback:
  path: /steam/login_check
  controller: Knojector\SteamAuthenticationBundle\Controller\SteamController::callback